export const formatoUnicoHeaders = [
  "Posición",
  "Año creación estructura y versión",
  "Código producto",
  "Tipo de Franqueo",
  "Código Etiquetador",
  "Número de contrato",
  "Número cliente",
  "Número de máquina de franquear",
  "Importe franqueado",
  "Código de Envío",
  "Nº de expedición",
  "Referencia de la expedición",
  "Autorización entregas parciales",
  "Total Bultos",
  "Numero de bulto",
  "Número manifiesto",
  "Código de Promoción",
  "Causa del Reenvío",
  "Nombre",
  "Apellido 1",
  "Apellido 2",
  "NIF",
  "Empresa",
  "Persona contacto",
  "Tipo dirección",
  "Dirección",
  "Direccion complemento",
  "Número",
  "Portal",
  "Bloque",
  "Escalera",
  "Piso",
  "Puerta",
  "Localidad",
  "Provincia",
  "CP",
  "ZIP",
  "País",
  "Oficina Elegida",
  "Destino apartado postal internacional",
  "Apartado Postal destino",
  "Teléfono contacto destinatario",
  "Email",
  "Código de HomePaq",
  "Tokenid Correospaq",
  "Referencia Cliente",
  "Referencia Cliente 2",
  "Referencia Cliente 3",
  "Modalidad de entrega",
  "Peso",
  "Largo",
  "Alto",
  "Ancho",
  "Seguro ",
  "Importe Seguro",
  "Reembolso",
  "Importe Reembolso",
  "Tipo Reembolso",
  "IBAN Reembolso",
  "Seguro LI",
  "Importe Seguro LI",
  "Reembolso LI",
  "Importe Reembolso LI",
  "Tipo Reembolso LI",
  "Número de cuenta LI",
  "Entrega Exclusiva Destinatario",
  "Formato de Prueba entrega",
  "Referencia eAR",
  "Información del remitente para eAr",
  "Indicador entrega con recogida",
  "Descripción envío a recoger",
  "Imprimir etiqueta recogida",
  "Código del envío de ida asociado",
  "Generar envío de vuelta",
  "Código del envío de vuelta",
  "Fecha de caducidad del envío de vuelta",
  "Envío de vuelta permite embalaje",
  "Código etiquetador del envío de vuelta",
  "Número SMS destinatario",
  "Número SMS remitente",
  "Idioma SMS Remitente",
  "Idioma SMS Destinatario",
  "Recogida a domicilio",
  "Número de intentos de entrega",
  "Tiempo de permanencia en lista",
  "Entrega en Fecha determinada",
  "Entrega en franja horaria",
  "Embalaje Prepagado",
  "Código embalaje prepago",
  "Código punto de admisión",
  "Frase promocional",
  "Fecha de depósito prevista",
  "Observaciones 1",
  "Observaciones 2",
  "Instrucciones de devolucion en caso de no entrega para paquetes internacionales",
  "Documento escaneado 1  ",
  "Acción documento 1",
  "Observaciones documento 1",
  "Documento escaneado 2",
  "Acción documento 2",
  "Observaciones documento 2",
  "Documento escaneado 3",
  "Accion documento 3",
  "Observaciones documento 3",
  "Horas de caducidad del envío de vuelta",
  "Entrega sin firma",
  "Tipo de modificación",
  "Tipo de Gestión",
  "Complejidad de gestión",
  "Autorización Previa a la Entrega",
  "Tipo de envío",
  "Envío comercial",
  "Factura superior a 500 euros",
  "DUA de exportación con Correos",
  "Cantidad-1",
  "Descripción de mercancía-1",
  "Peso neto-1",
  "Valor neto-1",
  "N Tarifario-1",
  "Descripción N Tarifario-1",
  "País de Origen-1",
  "Cantidad-2",
  "Descripción de mercancía-2",
  "Peso neto-2",
  "Valor neto-2",
  "N Tarifario-2",
  "Descripción N Tarifario-2",
  "País de Origen-2",
  "Cantidad-3",
  "Descripción de mercancía-3",
  "Peso neto-3",
  "Valor neto-3",
  "N Tarifario-3",
  "Descripción N Tarifario-3",
  "País de Origen-3",
  "Cantidad-4",
  "Descripción de mercancía-4",
  "Peso neto-4",
  "Valor neto-4",
  "N Tarifario-4",
  "Descripción N Tarifario-4",
  "País de Origen-4",
  "Cantidad-5",
  "Descripción de mercancía-5",
  "Peso neto-5",
  "Valor neto-5",
  "N Tarifario-5",
  "Descripción N Tarifario-5",
  "País de Origen-5",
  "Se adjunta factura",
  "Se adjunta licencia",
  "Se adjunta certificado",
  "Descripción factura adjunta",
  "Descripción licencia adjunta",
  "Descripción certificado adjunta",
  "Referencia aduanera del expedidor",
  "Referencia fiscal del importador",
  "Código del importador",
  "Número de IVA del importador",
  "Teléfono del importador",
  "Email del importador",
  "Contiene mercancías peligrosas",
  "Nombre",
  "Apellido 1",
  "Apellido 2",
  "Nif",
  "Empresa",
  "Persona contacto",
  "Tipo dirección",
  "Dirección",
  "Número",
  "Portal",
  "Bloque",
  "Escalera",
  "Piso",
  "Puerta",
  "Localidad",
  "Provincia",
  "CP",
  "ZIP",
  "Pais",
  "Teléfono contacto remitente",
  "Email",
  "Numero Apartado reembolso",
  "Codired pago giro por reembolso lista",
  "Fin De registro",
] as const
